/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package digitron;
//idemo na events, action i onda action.. i dode do ovog dijela gdje pisemo akciju       
//Ime variajbli se podesi kod buttona kod variablas name u code dijelu

import javax.swing.JOptionPane;

//Mi operacije i sve klase pravimo odvojeno kako zelimo i regularno a ovdje pisemo samo akcije za buttone i imamo izgled prozora
/**
 *
 * @author Korisnik
 */
public class kalk extends javax.swing.JFrame {
   

    /**
     * Creates new form kalk
     */
    public kalk() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Operator1 = new javax.swing.JTextField();
        Operator2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        oduzmi = new javax.swing.JButton();
        pomnozi = new javax.swing.JButton();
        podijeli = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        rezultat = new javax.swing.JTextField();

        jButton3.setText("jButton3");

        jLabel3.setText("Unesite drugi operand");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Unesite prvi operand");

        jLabel2.setText("Unesite drugi operand");

        Operator1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Operator1ActionPerformed(evt);
            }
        });

        jButton1.setText("+");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        oduzmi.setText("-");
        oduzmi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oduzmiActionPerformed(evt);
            }
        });

        pomnozi.setText("*");
        pomnozi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pomnoziActionPerformed(evt);
            }
        });

        podijeli.setText("/");
        podijeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                podijeliActionPerformed(evt);
            }
        });

        jLabel4.setText("Rezultat");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Operator1, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                            .addComponent(Operator2)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(oduzmi, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(pomnozi, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(podijeli, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 63, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rezultat, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Operator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Operator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(oduzmi)
                    .addComponent(pomnozi)
                    .addComponent(podijeli))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(rezultat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Operator1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Operator1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Operator1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
           double prvi = Double.parseDouble(Operator1.getText());
           double drugi = Double.parseDouble(Operator2.getText());
           Kontroler kk = new Kontroler(new model(prvi, drugi));
           rezultat.setText(String.valueOf(kk.saberi())); //rezultat je ime komponente textfield
    }//GEN-LAST:event_jButton1ActionPerformed

    private void oduzmiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oduzmiActionPerformed

           Kontroler kk = new Kontroler(new model(Operator1.getText(), Operator2.getText())); //OVDJE JE ISKORISTEN DRUGI KONSTRUKTOR KOJI
           //PRIMA STRING 
           rezultat.setText(String.valueOf(kk.oduzmi()));        // TODO add your handling code here:
    }//GEN-LAST:event_oduzmiActionPerformed

    private void pomnoziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pomnoziActionPerformed
         double prvi = Double.parseDouble(Operator1.getText());
           double drugi = Double.parseDouble(Operator2.getText());
           Kontroler kk = new Kontroler(new model(prvi, drugi));
           rezultat.setText(String.valueOf(kk.pomnozi()));
    }//GEN-LAST:event_pomnoziActionPerformed

    private void podijeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_podijeliActionPerformed
        //ovdje ubaciti try catch
        double prvi = Double.parseDouble(Operator1.getText());
           double drugi = Double.parseDouble(Operator2.getText());
           Kontroler kk = new Kontroler(new model(prvi, drugi));
           try
           {
           rezultat.setText(String.valueOf(kk.podijeli()));
           }
           catch (IllegalArgumentException ex)
           {
               JOptionPane.showMessageDialog(this,ex.getMessage(), "Greska", JOptionPane.ERROR_MESSAGE);
           }
    }//GEN-LAST:event_podijeliActionPerformed
    private model vratiPodatke()
    {
        return new model(Operator1.getText(), Operator2.getText()); //neka metoda za vracanje
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kalk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kalk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kalk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kalk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kalk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Operator1;
    private javax.swing.JTextField Operator2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton oduzmi;
    private javax.swing.JButton podijeli;
    private javax.swing.JButton pomnozi;
    javax.swing.JTextField rezultat;
    // End of variables declaration//GEN-END:variables
}
